In [4]:
import torch

x = torch.empty(2,2,3)
print(x)

tensor([[[4.3403e-34, 1.4013e-45, 3.8115e-34],
         [1.4013e-45, 4.3404e-34, 1.4013e-45]],

        [[3.8118e-34, 1.4013e-45, 4.3406e-34],
         [1.4013e-45, 8.1116e-36, 1.4013e-45]]])


In [5]:
torch.rand(2,2)

tensor([[0.2688, 0.6968],
        [0.1507, 0.7348]])

In [6]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [7]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [10]:
x=torch.tensor([2.5,0.1])
x

tensor([2.5000, 0.1000])